baseURL = 'https://eric.st-pierre.xyz/'
languageCode = 'en-us'
title = 'Éric St-Pierre'

summaryLength = 20

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'monokailight'
    tabWidth = 4

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[params]
  authors = ["Eric St-Pierre"]
  github = "https://github.com/SanPeter"
  linkedin = "https://www.linkedin.com/in/%C3%A9ric-st-pierre-0aa167145"
  bio = "Hi, my name is Éric St-Pierre. Briefly introduce yourself here."