baseURL = 'https://eric.st-pierre.xyz/'
languageCode = 'en-us'
title = 'Éric St-Pierre'

summaryLength = 50

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'monokailight'
    tabWidth = 4

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[params]
  authors = ["Eric St-Pierre"]
  copyrightInfo = '© 2020 - 2022 Éric St-Pierre'
  featuredArticles = 2
  colorTheme = "success"